suppressPackageStartupMessages({
  library(helios)
  library(dplyr)
  library(ggplot2)
  library(purrr)
  library(here)
  library(individual)
  library(ggplot2)
  library(purrr)
  library(patchwork)
  library(magrittr)
  library(cli)
  purrr::walk(list.files("R", full.names = TRUE), source)
})
